--RAINMAD SCRIPTS discord.gg/rainmad rainmad.com

cfg = {
    ['framework'] = 'qb', -- qb / esx / standalone
    ['items'] = { -- If you set framework to qb or esx, you need add this items to database or shared/items.lua
        ['spray_item'] = 'paint_spray',
        ['clear_graffiti_item'] = 'white_spray',
        ['clear_sticker_item'] = 'scraper',
    },
    ['standaloneCommands'] = { -- If you set framework to standalone, this commands will be active
        ['spray_command'] = 'decal',
        ['clear_graffiti_command'] = 'removegraffiti',
        ['clear_sticker_command'] = 'removesticker',
    },
    ['decalSizeStep'] = 0.1,
    ['minSize'] = 0.1,           -- Minimum decal size
    ['maxSize'] = 5.0,           -- Maximum decal size
    ['paintDelay'] = 5,          -- Delay for graffiti spray to wall
    ['removeGraffitiDelay'] = 5, -- Delay for remove graffiti spray from wall
    ['disableVehicleStickers'] = false,
    ['disableGraffiti'] = false,

    -- admin commands
    ['permanentDecalCommand'] = 'permadecal',
    ['adminDeleteVehicleDecalCommand'] = 'adminremovesticker',
    ['adminDeleteGraffitiCommand'] = 'adminremovegraffiti',

    ['locales'] = { -- All strings used in the script
        ['decalslist'] = 'Decal List',
        ['select'] = 'Select',
        ['selected'] = 'Selected',
        ['placementmode'] = 'Placement Mode',
        ['backtoplacementmode'] = 'Back to Placement Mode',
        ['needtochoosedecal'] = 'First you need to choose decal',
        ['xsize'] = 'X Size',
        ['ysize'] = 'Y Size',
        ['savepos'] = 'Save Position',
        ['decalcolor'] = 'Decal Color',
        ['savedecal'] = 'Save Decal',
        ['rotation'] = 'Rotation',
        ['mirror'] = 'Mirror',
        ['permanent'] = 'Permanent',
        ['nomirror'] = 'No mirror can be applied to selected area',
        ['sticker_remove_editor'] = '~INPUT_CELLPHONE_RIGHT~ next sticker \n~INPUT_CELLPHONE_LEFT~ previous sticker \n~INPUT_CELLPHONE_SELECT~ remove sticker\n~INPUT_CELLPHONE_CANCEL~ exit \nSelected sticker: ',
        ['no_vehicle'] = 'No nearby vehicle',
        ['no_plate'] = 'No vehicle plate',
        ['no_graffiti'] = 'No nearby graffiti',
        ['no_sticker'] = 'This vehicle does not have decal!',
        ['sticker_success'] = 'You succesfuly placed the decal!',
        ['sticker_remove'] = 'You succesfuly removed the decal!',
        ['no_job'] = 'You do not have job for this decal!',
        ['wrong_owner'] = 'This vehicle does not belong to you',
        ['stop_remove'] = 'You stopped remove sticker',
        ['not_admin'] = 'You are not admin',
        ['permanent_graffiti'] = 'This graffiti is permanent',
    },
}

--If you want add job to any sticker, just add new line like: job = 'police'
--Do not add URL with this. Example: ?width=671&height=671 or other url extensions
cfg['decals'] = {
    {
        label = 'RAINMAD',
        url = 'https://cdn.discordapp.com/attachments/1066929380300955689/1119314739080736820/logo.png',
    },
    {
        label = 'redline',
        image = 'decals/vehicle/redline.png',
        textureName = 'redline',
        textureDict = 'vehicledecals',
    },
    {
        label = '5Zigen',
        image = 'decals/vehicle/5Zigen.png',
        textureName = '5Zigen',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Akagi Red Suns',
        image = 'decals/vehicle/AkagiRedSuns.png',
        textureName = 'Akagi Red Suns',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Akina Speed Stars',
        image = 'decals/vehicle/AkinaSpeedStars.png',
        textureName = 'Akina Speed Stars',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Akina Speed Stars 2',
        image = 'decals/vehicle/AkinaSpeedStars2.png',
        textureName = 'Akina Speed Stars 2',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Blick',
        image = 'decals/vehicle/Blick.png',
        textureName = 'Blick',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Dog JDM',
        image = 'decals/vehicle/DogJDM.png',
        textureName = 'Dog JDM',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Edelbrock01',
        image = 'decals/vehicle/Edelbrock01.png',
        textureName = 'Edelbrock01',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Endless',
        image = 'decals/vehicle/Endless.png',
        textureName = 'Endless',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Flames Red Purple',
        image = 'decals/vehicle/FlamesRedPurple.png',
        textureName = 'Flames Red Purple',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Fujiwara Tofu Initial D',
        image = 'decals/vehicle/FujiwaraTofuInitialD.png',
        textureName = 'Fujiwara Tofu Initial D',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Fukaru Plain',
        image = 'decals/vehicle/FukaruPlain.png',
        textureName = 'Fukaru Plain',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Fukaru',
        image = 'decals/vehicle/Fukaru.png',
        textureName = 'Fukaru',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Genic',
        image = 'decals/vehicle/Genic.png',
        textureName = 'Genic',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Initial D',
        image = 'decals/vehicle/InitialD.png',
        textureName = 'Initial D',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Itasha Racing Red',
        image = 'decals/vehicle/ItashaRacingRed.png',
        textureName = 'ItashaRacingRed',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Lunati',
        image = 'decals/vehicle/Lunati.png',
        textureName = 'Lunati',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Momo01',
        image = 'decals/vehicle/Momo01.png',
        textureName = 'Momo01',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Night Kids Mini',
        image = 'decals/vehicle/NightKidsMini.png',
        textureName = 'Night Kids Mini',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Night Kids Mini 2',
        image = 'decals/vehicle/NightKidsMini2.png',
        textureName = 'Night Kids Mini 2',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Nismo',
        image = 'decals/vehicle/Nismo.png',
        textureName = 'Nismo',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Nismo2',
        image = 'decals/vehicle/Nismo2.png',
        textureName = 'Nismo2',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Nissan',
        image = 'decals/vehicle/Nissan.png',
        textureName = 'Nissan',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Nos01',
        image = 'decals/vehicle/Nos01.png',
        textureName = 'Nos01',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Nos02',
        image = 'decals/vehicle/Nos02.png',
        textureName = 'Nos02',
        textureDict = 'vehicledecals',
    },
    {
        label = 'RockstarGamesLogo',
        image = 'decals/vehicle/RockstarGamesLogo.png',
        textureName = 'Rockstar Games Logo',
        textureDict = 'vehicledecals',
    },
    {
        label = 'TenzoR',
        image = 'decals/vehicle/TenzoR.png',
        textureName = 'Tenzo R',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Toyo Tires 01',
        image = 'decals/vehicle/ToyoTires01.png',
        textureName = 'Toyo Tires01',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Toyo Tires 02',
        image = 'decals/vehicle/ToyoTires02.png',
        textureName = 'Toyo Tires02',
        textureDict = 'vehicledecals',
    },
    {
        label = 'TypeR',
        image = 'decals/vehicle/TypeR.png',
        textureName = 'TypeR',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Veilside',
        image = 'decals/vehicle/Veilside.png',
        textureName = 'Veilside',
        textureDict = 'vehicledecals',
    },
    {
        label = 'Viper',
        image = 'decals/vehicle/Viper.png',
        textureName = 'Viper',
        textureDict = 'vehicledecals',
    },

    {
        label = 'AlfabetAlphabetSkull',
        image = 'decals/graffiti/AlfabetAlphabetSkull.png',
        textureName = 'Alfabet Alphabet Skull',
        textureDict = 'graffiti',
    },
    {
        label = 'Alice Pasquini Rome 2014 Veronica Rossi',
        image = 'decals/graffiti/AlicePasquiniRome2014VeronicaRossi.png',
        textureName = 'Alice Pasquini Rome 2014 Veronica Rossi',
        textureDict = 'graffiti',
    },
    {
        label = 'Bacon Rouen',
        image = 'decals/graffiti/BaconRouen.png',
        textureName = 'Bacon Rouen',
        textureDict = 'graffiti',
    },
    {
        label = 'Burbon Sassy',
        image = 'decals/graffiti/BurbonSassy.png',
        textureName = 'Burbon Sassy',
        textureDict = 'graffiti',
    },
    {
        label = 'Bushwick mural claudia bianca',
        image = 'decals/graffiti/Bushwickmuralclaudiabianca.png',
        textureName = 'Bushwick mural claudia bianca',
        textureDict = 'graffiti',
    },
    {
        label = 'Donald Duck',
        image = 'decals/graffiti/DonaldDuck.png',
        textureName = 'Donald Duck',
        textureDict = 'graffiti',
    },
    {
        label = 'Freestyle',
        image = 'decals/graffiti/Freestyle.png',
        textureName = 'Freestyle',
        textureDict = 'graffiti',
    },
    {
        label = 'Gas Mask',
        image = 'decals/graffiti/GasMask.png',
        textureName = 'Gas Mask',
        textureDict = 'graffiti',
    },
    {
        label = 'Girl Pink Blue',
        image = 'decals/graffiti/GirlPinkBlue.png',
        textureName = 'Girl Pink Blue',
        textureDict = 'graffiti',
    },
    {
        label = 'Girl Purple',
        image = 'decals/graffiti/GirlPurple.png',
        textureName = 'Girl Purple',
        textureDict = 'graffiti',
    },
    {
        label = 'Green Skull',
        image = 'decals/graffiti/GreenSkull.png',
        textureName = 'Green Skull',
        textureDict = 'graffiti',
    },
    {
        label = 'Hip-Hop',
        image = 'decals/graffiti/Hip-Hop.png',
        textureName = 'Hip-Hop',
        textureDict = 'graffiti',
    },
    {
        label = 'Holy Spray',
        image = 'decals/graffiti/HolySpray.png',
        textureName = 'Holy Spray',
        textureDict = 'graffiti',
    },
    {
        label = 'Horror Freddy Frankenstein',
        image = 'decals/graffiti/HorrorFreddyFrankenstein.png',
        textureName = 'Horror Freddy Frankenstein',
        textureDict = 'graffiti',
    },
    {
        label = 'Joker',
        image = 'decals/graffiti/Joker.png',
        textureName = 'Joker',
        textureDict = 'graffiti',
    },
    {
        label = 'Junk',
        image = 'decals/graffiti/Junk.png',
        textureName = 'Junk',
        textureDict = 'graffiti',
    },
    {
        label = 'Kampong Glam',
        image = 'decals/graffiti/KampongGlam.png',
        textureName = 'Kampong Glam',
        textureDict = 'graffiti',
    },
    {
        label = 'LA Girl',
        image = 'decals/graffiti/LAGirl.png',
        textureName = 'LA Girl',
        textureDict = 'graffiti',
    },
    {
        label = 'MIST',
        image = 'decals/graffiti/MIST.png',
        textureName = 'MIST',
        textureDict = 'graffiti',
    },
    {
        label = 'New York Kid',
        image = 'decals/graffiti/NewYorkKid.png',
        textureName = 'New York Kid',
        textureDict = 'graffiti',
    },
    {
        label = 'Noe Two 1',
        image = 'decals/graffiti/NoeTwo1.png',
        textureName = 'Noe Two 1',
        textureDict = 'graffiti',
    },
    {
        label = 'Peace',
        image = 'decals/graffiti/Peace.png',
        textureName = 'Peace',
        textureDict = 'graffiti',
    },
    {
        label = 'Pink Girls Acc',
        image = 'decals/graffiti/PinkGirlsAcc.png',
        textureName = 'Pink Girls Acc',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_atomizer1_d',
        image = 'decals/graffiti/prop_atomizer1_d.png',
        textureName = 'prop_atomizer1_d',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_atomizer2_d',
        image = 'decals/graffiti/prop_atomizer2_d.png',
        textureName = 'prop_atomizer2_d',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_car_declasse2_d',
        image = 'decals/graffiti/prop_car_declasse2_d.png',
        textureName = 'prop_car_declasse2_d',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_car_gt500_d',
        image = 'decals/graffiti/prop_car_gt500_d.png',
        textureName = 'prop_car_gt500_d',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_duster_d',
        image = 'decals/graffiti/prop_duster_d.png',
        textureName = 'prop_duster_d',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_duster2_d',
        image = 'decals/graffiti/prop_duster2_d.png',
        textureName = 'prop_duster2_d',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_facestripe_d',
        image = 'decals/graffiti/prop_facestripe_d.png',
        textureName = 'prop_facestripe_d',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_gang_d',
        image = 'decals/graffiti/prop_gang_d.png',
        textureName = 'prop_gang_d',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_impotentrage',
        image = 'decals/graffiti/prop_impotentrage.png',
        textureName = 'prop_impotentrage',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_infernus_d',
        image = 'decals/graffiti/prop_infernus_d.png',
        textureName = 'prop_infernus_d',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_octomask_d',
        image = 'decals/graffiti/prop_octomask_d.png',
        textureName = 'prop_octomask_d',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_peach_d',
        image = 'decals/graffiti/prop_peach_d.png',
        textureName = 'prop_peach_d',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_popart1',
        image = 'decals/graffiti/prop_popart1.png',
        textureName = 'prop_popart1',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_popart2_d',
        image = 'decals/graffiti/prop_popart2_d.png',
        textureName = 'prop_popart2_d',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_popart3_d',
        image = 'decals/graffiti/prop_popart3_d.png',
        textureName = 'prop_popart3_d',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_popbrand1_d',
        image = 'decals/graffiti/prop_popbrand1_d.png',
        textureName = 'prop_popbrand1_d',
        textureDict = 'graffiti',
    },
    {
        label = 'prop_popbrand2_d',
        image = 'decals/graffiti/prop_popbrand2_d.png',
        textureName = 'prop_popbrand2_d',
        textureDict = 'graffiti',
    },
    {
        label = 'Scarf Girl',
        image = 'decals/graffiti/ScarfGirl.png',
        textureName = 'Scarf Girl',
        textureDict = 'graffiti',
    },
    {
        label = 'Sinister',
        image = 'decals/graffiti/Sinister.png',
        textureName = 'Sinister',
        textureDict = 'graffiti',
    },
    {
        label = 'Skull Spray Can',
        image = 'decals/graffiti/SkullSprayCan.png',
        textureName = 'Skull Spray Can',
        textureDict = 'graffiti',
    },
    {
        label = 'Smoker',
        image = 'decals/graffiti/Smoker.png',
        textureName = 'Smoker',
        textureDict = 'graffiti',
    },
    {
        label = 'Sofles Mural',
        image = 'decals/graffiti/SoflesMural.png',
        textureName = 'Sofles Mural',
        textureDict = 'graffiti',
    },
    {
        label = 'Toronta Red Green',
        image = 'decals/graffiti/TorontaRedGreen.png',
        textureName = 'Toronta Red Green',
        textureDict = 'graffiti',
    },
    {
        label = 'Tupac 2Pac',
        image = 'decals/graffiti/Tupac2Pac.png',
        textureName = 'Tupac 2Pac',
        textureDict = 'graffiti',
    },
    {
        label = 'Twin Girls',
        image = 'decals/graffiti/TwinGirls.png',
        textureName = 'Twin Girls',
        textureDict = 'graffiti',
    },
    {
        label = 'UFO Green',
        image = 'decals/graffiti/UFOGreen.png',
        textureName = 'UFO Green',
        textureDict = 'graffiti',
    },
}
