Config = {}

Config.Settings = {
  ['sql'] = 'oxmysql',
  ['Job'] = {
    ['UseJob'] = true,
    ['BossOnly'] = true,
  },
  ['Notify'] = 'ps-ui',
  ['Payments'] = {
    ['UsePayment'] = true,
    ['RenewedBanking'] = true,
    ['moneyType'] = 'bank',
  },
}

Config.engineLocations = {
  ["TestingZone"] = { 
    ["coords"] = vector3(998.56, -1499.51, 30.9),
    ["size"] = 5.0,
    ["heading"] = 0.0, 
    ["debug"] = false, 
    ["authorizedJob"] = "srs", 
    ["inVehicle"] = "Press E to engineswap", 
    ["outVehicle"] = "You need to be in a vehicle!", 
  },
}

Config.Swaps = {
  [`r34sound`] = { 	
    custom = true,
    price = 0,
    label = 'RB26DE Twin Turbo', 	
    soundname = 'r34sound', 
  },
  [`f20c`] = { 	
    custom = true,
    price = 0, 	
    label = 'Civic F20C', 	
    soundname = 'f20c', 
  },
  [`aq2jzgterace`] = { 	
    custom = true,
    price = 0, 	
    label = 'Supra 2JZ GTE Twin Turbo', 	
    soundname = 'aq2jzgterace', 
  },
  [`rotary7`] = { 	
    custom = true,
    price = 0, 	
    label = 'RX7 13B-REW Twin-Rotor Twin Turbo', 	
    soundname = 'rotary7', 
  },
  [`fordvoodoo`] = {   	
    custom = true,
    price = 0, 	
    label = 'Ford Mustang v8',   
    soundname = 'fordvoodoo',    
  },
  [`f10m5`] = {   	
    custom = true,
    price = 0, 	
    label = 'BMW M5 f10 ',   	
    soundname = 'f10m5',    
  },
  [`lfasound`] = {   	
    custom = true, 
    price = 0, 	
    label = 'LFA V10',   	
    soundname = 'lfasound',    
  },
  [`elegyx`] = {   	
    custom = true,   	
    price = 0,	
    label = 'GTR R35',   	
    soundname = 'elegyx',    
  },
  [`ta028viper`] = {   	
    custom = true,
    price = 0, 	
    label = 'Viper V10',   	
    soundname = 'ta028viper',    
  },
  [`porsche57v10`] = {   	
    custom = true,   	
    price = 0,
    label = 'Porsche 57 V10',   	
    soundname = 'porsche57v10',    
  },
  [`s15sound`] = {   	
    custom = true,
    price = 0, 	
    label = 'S15 SR20',   	
    soundname = 's15sound',    
  },
  [`gt3rstun`] = {   	
    custom = true,
    price = 0, 	
    label = 'Flat 6',   	
    soundname = 'gt3rstun',    
  },
  [`m297zonda`] = {   	
    custom = true,  	
    price = 0,
    label = 'Zonda V12',   	
    soundname = 'm297zonda',    
  },
  [`aq06nhonc30a`] = {   	
    custom = true,   	
    price = 0, 
    label = 'NSX',   	
    soundname = 'aq06nhonc30a',    
  },
  [`p60b40`] = {   	
    custom = true,
    price = 0, 	
    label = 'BMW Engine M3',   	
    soundname = 'p60b40',    
  },
  [`aqls7raceswap`] = {   	
    custom = true,
    price = 0, 	
    label = 'C7 V8',   	
    soundname = 'aqls7raceswap',    
  },
  [`aqtoy2jzstock`] = {   	
    custom = true,   	
    price = 0,  
    label = 'Supra 2JZ GTE',   	
    soundname = 'aqtoy2jzstock',    
  },
  [`bgw16`] = {   	
    custom = true,
    price = 0, 	
    label = 'Bugatti W16',   	
    soundname = 'bgw16',    
  },
  [`cvpiv8`] = {   	
    custom = true,
    price = 0, 	
    label = 'cvpi V8',   
    soundname = 'cvpiv8',    
  },
  [`cw2019`] = {   	
    custom = true, 
    price = 0, 	
    label = 'Senna engine',   	
    soundname = 'cw2019',    
  },
  [`ea888`] = {   	
    custom = true,
    price = 0, 	
    label = 'VW EA-888',   	
    soundname = 'ea888',    
  },
  [`ecoboostv6`] = {   	
    custom = true,
    price = 0, 	
    label = 'Ford explorer V6',   	
    soundname = 'ecoboostv6',    
  },
  [`ftypesound`] = {   	
    custom = true,  	
    price = 0,
    label = 'Ftype engine',   	
    soundname = 'ftypesound',    
  },
  [`hemisound`] = {   	
    custom = true,
    price = 0, 	
    label = 'Hemi V8 engine',   	
    soundname = 'dodgehemihellcat',    
  },
  [`lambov10`] = {   	
    custom = true,   	
    price = 0,   	
    label = 'lambo V10',   	
    soundname = 'lambov10',    
  },
  [`lgcy04murciv12`] = {   	
    custom = true,
    price = 0, 	
    label = 'Lambo V12',   	
    soundname = 'lgcy04murciv12',    
  },
  [`mbnzc63eng`] = {   	
    custom = true,
    price = 0, 	
    label = 'Mercedes C63 V8',   	
    soundname = 'mbnzc63eng',   
  },
  [`n4g63t`] = {   	
    custom = true,
    price = 0, 	
    label = 'Evo engine',   	
    soundname = 'n4g63t',    
  },
  [`npcul`] = {   	
    custom = true,   	
    price = 0, 	
    label = 'RRoyce',   	
    soundname = 'npcul',    
  },
  [`npolchar`] = {   	
    custom = true,
    price = 0, 	
    label = 'charger V8',   	
    soundname = 'npolchar',    
  },
  [`s85b50`] = {   	
    custom = true,   	
    price = 0,   	
    label = 'Victor V8',   	
    soundname = 's85b50',    
  },
  [`subaruej20`] = {   	
    custom = true,
    price = 0, 	
    label = 'subaru boxer',   	
    soundname = 'subaruej20',    
  },
  [`ta488f154`] = {   	
    custom = true,
    price = 0, 	
    label = 'F488 V8',   	
    soundname = 'ta488f154',    
  },
  [`taaud40v8`] = {   	
    custom = true,
    price = 0, 	
    label = 'Audi v8',   	
    soundname = 'taaud40v8',    
  },
  [`trumpetzr`] = {   	
    custom = true,
    price = 0, 	
    label = 'VQ Straight 6',   	
    soundname = 'trumpetzr',    
  },
  [`sultanrsv8`] = {   	
    custom = true,
    price = 0, 	
    label = 'Sultan RS V8',   	
    soundname = 'sultanrsv8',    
  },
  [`aq46forgtebv6`] = {   	
    custom = true,
    price = 0, 	
    label = 'AQ46 GTE V6',   	
    soundname = 'aq46forgtebv6',    
  },
  [`aq58honk20a`] = {   	
    custom = true,
    price = 0, 	
    label = 'AQ58 Honk 20A',   	
    soundname = 'aq58honk20a',    
  },
  [`lg18bmwm4`] = {   	
    custom = true,
    price = 0, 	
    label = 'BMW M4',   	
    soundname = 'lg18bmwm4',    
  },
  [`lg157por911`] = {   	
    custom = true,
    price = 0, 	
    label = 'Porsche 911',   	
    soundname = 'lg157por911',    
  },
  [`ta4b11`] = {   	
    custom = true,
    price = 0, 	
    label = 'B11',   	
    soundname = 'ta4b11',    
  },
  [`ta025ea888`] = {   	
    custom = true,
    price = 0, 	
    label = 'Astra VXR',   	
    soundname = 'ta025ea888',    
  },
  [`avesv`] = {   	
    custom = true,
    price = 0, 	
    label = 'Avesv',   	
    soundname = 'avesv',    
  },
  [`brabus850`] = {   	
    custom = true,
    price = 0, 	
    label = 'Brabus V8',   	
    soundname = 'brabus850',    
  },
  [`diablov12`] = {   	
    custom = true,
    price = 0, 	
    label = 'Diablo V12',   	
    soundname = 'diablov12',    
  },
  [`f40v8`] = {   	
    custom = true,
    price = 0, 	
    label = 'F40 V8',   	
    soundname = 'f40v8',    
  },
  [`f50v12`] = {   	
    custom = true,
    price = 0, 	
    label = 'F50 V12',   	
    soundname = 'f50v12',    
  },
  [`ferrarif12`] = {   	
    custom = true,
    price = 0, 	
    label = 'Ferrari F12',   	
    soundname = 'ferrarif12',    
  },
  [`gt3flat6`] = {   	
    custom = true,
    price = 0, 	
    label = 'GT3 Flat 6',   	
    soundname = 'gt3flat6',    
  },
  [`murciev12`] = {   	
    custom = true,
    price = 0, 	
    label = 'Murci V12',   	
    soundname = 'murciev12',    
  },
  [`musv8`] = {   	
    custom = true,
    price = 0, 	
    label = 'Mustang V8',   	
    soundname = 'musv8',    
  },
  [`predatorv8`] = {   	
    custom = true,
    price = 0, 	
    label = 'Predator V8',   	
    soundname = 'predatorv8',    
  },
  [`rb26dett`] = {   	
    custom = true,
    price = 0, 	
    label = 'RB26',   	
    soundname = 'rb26dett',    
  },
  [`sestov10`] = {   	
    custom = true,
    price = 0, 	
    label = 'Sesto V10',   	
    soundname = 'sestov10',    
  },
  [`shonen`] = {   	
    custom = true,
    price = 0, 	
    label = 'Shonen',   	
    soundname = 'shonen',    
  },
  [`toysupmk4`] = {   	
    custom = true,
    price = 0, 	
    label = 'Supra Mk4',   	
    soundname = 'toysupmk4',    
  },
  
  -- bikes
  [`suzukigsx`] = {   	
    custom = true,
    price = 0,  	
    label = 'Bike suzukigsx',   	
    soundname = 'suzukigsxr1k',    
  },
  [`tayamahar1`] = {   	
    custom = true,
    price = 0, 	
    label = 'Bike tayamahar1',   	
    soundname = 'tayamahar1',    
  },
  [`s1000rr`] = {   	
    custom = true,
    price = 0, 	
    label = 'Bike bmws1krreng',   	
    soundname = 'bmws1krreng',    
  },
}
